version: "3.9"

services:
  flask_app:
    container_name: flask_weather_app
    image: python
    build: .
    ports:
      - "4000:4000"
    environment:
      - DB_URL=postgresql://postgres:postgres@flask_weather_db:5432/postgres
    depends_on:
      - flask_db
  flask_db:
    container_name: flask_weather_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}